version: "3.9"
services:
  db:
    container_name: upload_db
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: Admin@123
      MYSQL_DATABASE: upload_db
    ports:
      - 3306:3306
    volumes:
      - upload_db_vol:/var/lib/mysql

volumes:
  upload_db_vol:
